spring:
    application:
        name: UserService
    datasource:
        url: ${database_address}
        driver-class-name: org.postgresql.Driver
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update
        show-sql: true

server:
    port: 8082
    address: 0.0.0.0

jwt:
    secret: 612987369178593529498726408152048751027846012